name: constexpr
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**/doc/**'
      - '**.md'

jobs:
  Linux-Ubuntu-22:
    name: Linux Ubuntu 22
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        # Clang should be used for constexpr tests, it's the only compiler that catch complex cases for sure
        cxx: [clang++-15]
    env:
        CXX: ${{matrix.cxx}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: CMake
        run: cmake -S test -B build -DCMAKE_BUILD_TYPE="Release" -DTEST_CONSTEXPR=ON
      - name: Build
        run: cmake --build build
      - name: Run tests
        run: |
          cd build
          ctest --verbose --output-on-failure

