name: Linux
on: workflow_dispatch

jobs:
  Linux-Ubuntu-20:
    name: Linux Ubuntu 20
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cxx: [g++-10, g++-9, clang++-12, clang++-10]
    env:
        CXX: ${{matrix.cxx}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: CMake
        run: cmake -S test -B build -DCMAKE_BUILD_TYPE="Release"
      - name: Build
        run: cmake --build build
      - name: Run tests
        run: |
          cd build
          ctest --verbose

  Linux-Ubuntu-18:
    name: Linux Ubuntu 18
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        cxx: [g++-7, clang++-9]
    env:
        CXX: ${{matrix.cxx}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: CMake
        run: cmake -S test -B build -DCMAKE_BUILD_TYPE="Release"
      - name: Build
        run: cmake --build build
      - name: Run tests
        run: |
          cd build
          ctest --verbose

