name: macOS
on: workflow_dispatch

jobs:
  macOS-Xcode:
    name: macOS Xcode
    runs-on: macos-11
    strategy:
      matrix:
        xcode: [13.2.1, 12.5.1, 11.7]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: CMake
        run: cmake -S test -B build -DCMAKE_BUILD_TYPE="Release"
      - name: Build
        run: cmake --build build
      - name: Run tests
        run: |
          cd build
          ctest --verbose
